### PR TITLE
Added building instructions to get up and running smoothly

### PR DESCRIPTION
**Pull request by gilescope**
These instructions work for me on a fairly clean windows 10 box. Hopefully this will get people up and testing faster.

### CODE REVIEW

**Comment by gilescope** [comment]
Fixes #23?

**Comment by hithomasmorelli** [comment]
Not sure if commenting out the checks for required `sonar` properties is the best idea - then other parts of the app that depend on them might function weirdly. Maybe best just to add them to `gradle.properties` (or better, `gradle-local.properties`) as discussed in #2?

**Comment by gilescope** [comment]
Ok how does that look @hithomasmorelli ?

(I can see we're missing a CI system for building against PRs. I'll raise that as a separate issue.)

**Comment by hithomasmorelli** [comment]
Looks better, but I don't know enough to give proper judgement on the PR! Hopefully someone who knows more than me can do that

**Comment by gilescope** [comment]
@edent thoughts on this PR?

**Comment by adarrel753** [comment]
Thanks for the instructions, they helped me a lot  - I'm not an Android developer, I'm a database guy. Anyway I got the app to build and have my phone connected via USB with the USB Debugging option switched on. When I run gradlew I one of the unit tests fails though:

```
> Task :app:connectedDebugAndroidTest
Starting 2 tests on SM-A705FN - 10

uk.nhs.nhsx.sonar.android.app.AndroidSecretKeyStorageTest > testAll[SM-A705FN - 10] SUCCESS

[InstrumentationResultParser]: test run failed: 'Instrumentation run failed due to 'Process crashed.''
[XmlResultReporter]: XML test result file generated at C:\android\COVID-19-app-Android-BETA-master\app\build\outputs\androidTest-results\connected\TEST-SM-A705FN - 10-app-.xml. Total tests 1, passed 1,

> Task :app:connectedDebugAndroidTest
Tests on SM-A705FN - 10 failed: Instrumentation run failed due to 'Process crashed.'
DeviceConnector 'SM-A705FN - 10': uninstalling app.android.covid19.test
DeviceConnector 'SM-A705FN - 10': uninstalling app.android.covid19
Task :app:connectedDebugAndroidTest in app Finished

> Task :app:connectedDebugAndroidTest FAILED
:app:connectedDebugAndroidTest (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 39.451 secs.
:app:outputInstrumentationErrors (Thread[Execution worker for ':' Thread 2,5,main]) started.

> Task :app:outputInstrumentationErrors
Task :app:outputInstrumentationErrors in app Starting
Custom actions are attached to task ':app:outputInstrumentationErrors'.
Caching disabled for task ':app:outputInstrumentationErrors' because:
  Caching has not been enabled for the task
Task ':app:outputInstrumentationErrors' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Task :app:outputInstrumentationErrors in app Finished
:app:outputInstrumentationErrors (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.025 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///C:/android/COVID-19-app-Android-BETA-master/app/build/reports/androidTests/connected/index.html

```

**Comment by adarrel753** [comment]
Note: I have added a new issue (https://github.com/nhsx/COVID-19-app-Android-BETA/issues/40) about this, as your instructions were fine :)

**Pull request closed without merging**
